- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Template haproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart haproxy

- name: Install prometheus haproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter
    state: present

- name: Template haproxy exporter config
  ansible.builtin.template:
    src: prom_ha_exp.conf.j2
    dest: /etc/default/prometheus-haproxy-exporter
    mode: '0644'      
  notify: Restart haproxy exporter

- name: Start haproxy service
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Start haproxy prometheus exporter service
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true

- name: Assign cnames
  include_role:
    name: "cname"
  vars:
    service: "lb{{inventory_hostname | replace('serobon','')}}"