{
 "title": "Backups",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Full MySQL backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"serobon\",service=\"mysql\",type=\"full\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last MySQL backup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"serobon\",service=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full InfluxDB backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"serobon\",service=\"influxdb\",type=\"full\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last InfluxDB backup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"serobon\",service=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}