- name: Add user 'agama'
  ansible.builtin.user:
    name: agama
    state: present
    shell: /bin/bash
    create_home: yes

- name: Create directory '/opt/agama'
  ansible.builtin.file:
    path: /opt/agama
    mode: '0755'
    owner: agama
    state: directory

- name: Install AGAMA dependencies
  ansible.builtin.apt:
    name:
      - python3
      - python3-flask
      - python3-flask-sqlalchemy
      - python3-pymysql  
      - sqlite3
    state: present

- name: Install 'agama.py' to '/opt/agama'
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py

