- name: Install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Modify prometheus configuration
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart prometheus

- name: Modify default parameters of prometheus
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/prometheus
  notify: Restart prometheus
  
- name: Start prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

