- name: Install bind9 and prometheus-bind-exporter
  ansible.builtin.apt:
    name: 
      - bind9
    state: present

- name: Extract Bind9 exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus-community/bind_exporter/releases/download/v0.7.0/bind_exporter-0.7.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    extra_opts: [ "--strip-components=1", "--wildcards", "--no-anchored", "bind_exporter" ]

- name: Create symlink to Bind9 exporter executable
  ansible.builtin.file:
    src: /opt/bind_exporter
    dest: /usr/local/bin/prometheus-bind-exporter
    state: link

- name: Create Bind9 exporter systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/bind_exporter.service
    content: |
      [Unit]
      Description=Exporter for Bind9
      Wants=network-online.target
      After=network.target

      [Service]
      User=bind
      Group=bind
      Type=simple
      ExecStart=/usr/local/bin/prometheus-bind-exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd
    - Restart bind9-exporter

- name: Create bind9 config
  ansible.builtin.template:
    dest: /etc/bind/named.conf.{{ item }}
    src: named.conf.{{ item }}.j2
    mode: '0644'
  loop:
    - local
    - options
  notify: Restart bind9

- name: Create database config
  ansible.builtin.template:
    dest: /var/cache/bind/db.{{ domain_name }}
    src: db.{{ domain_name }}.j2
    mode: '0644'
  notify: Restart bind9

- name: Startup on boot
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9